// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{web-ApiKey}',
    appId: '{web-AppId}',
    messagingSenderId: '{web-MessageSenderId}',
    projectId: '{web-ProjectId}',
    authDomain: '{web-AuthDomain}',
    storageBucket: '{web-StorageBucket}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{android-ApiKey}',
    appId: '{android-AppId}',
    messagingSenderId: '{android-MessageSenderId}',
    projectId: '{android-ProjectId}',
    storageBucket: '{android-StorageBucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{ios-ApiKey}',
    appId: '{ios-AppId}',
    messagingSenderId: '{ios-MessageSenderId}',
    projectId: '{ios-ProjectId}',
    storageBucket: '{ios-StorageBucket}',
    iosBundleId: 'com.example.tableOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '{macos-ApiKey}',
    appId: '{macos-AppId}',
    messagingSenderId: '{macos-MessageSenderId}',
    projectId: '{macos-ProjectId}',
    storageBucket: '{macos-StorageBucket}',
    iosBundleId: 'com.example.tableOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '{windows-ApiKey}',
    appId: '{windows-AppId}',
    messagingSenderId: '{windows-MessageSenderId}',
    projectId: '{windows-ProjectId}',
    authDomain: '{windows-AuthDomain}',
    storageBucket: '{windows-StorageBucket}',
  );
}
